/*
 * ***** BEGIN GPL LICENSE BLOCK *****
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * The Original Code is Copyright (C) 2005 Blender Foundation.
 * All rights reserved.
 *
 * The Original Code is: all of this file.
 *
 * Contributor(s): Robin Allen
 *
 * ***** END GPL LICENSE BLOCK *****
 */

#include "node_shader_util.hh"

static blender::bke::bNodeSocketTemplate  sh_node_in[] = {{SOCK_SHADER,
                                            N_("Scattered object 1"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_SHADER,
                                            N_("Scattered object 2"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_SHADER,
                                            N_("Scattered object 3"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_SHADER,
                                            N_("Scattered object 4"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_INT,
                                            N_("Object selection seed"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1000000.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_SHADER,
                                            N_("Object selection map"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_INT,
                                            N_("DimensionX"),
                                            1.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1.0f,
                                            1000.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_INT,
                                            N_("DimensionY"),
                                            1.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1.0f,
                                            1000.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_INT,
                                            N_("DimensionZ"),
                                            1.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1.0f,
                                            1000.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Offsets"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_SHADER,
                                            N_("Culling map"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_FLOAT,
                                            N_("Culling min"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_FLOAT,
                                            N_("Culling max"),
                                            1.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Reference up direction"),
                                            0.f,
                                            1.f,
                                            0.f,
                                            0.0f,
                                            -1.f,
                                            1.f,
                                            PROP_DIRECTION,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Reference up point"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Reference front direction"),
                                            0.f,
                                            1.f,
                                            0.f,
                                            0.0f,
                                            -1.f,
                                            1.f,
                                            PROP_DIRECTION,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Reference front point"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Rotation min"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Rotation max"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_FLOAT,
                                            N_("Rotation step"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1000000.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_SHADER,
                                            N_("Rotation map"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Scale min"),
                                            1.0f,
                                            1.0f,
                                            1.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Scale max"),
                                            1.0f,
                                            1.0f,
                                            1.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_FLOAT,
                                            N_("Scale step"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1000000.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_SHADER,
                                            N_("Scale map"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Translation min"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_VECTOR,
                                            N_("Translation max"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            -1000000.0f,
                                            1000000.0f,
                                            PROP_XYZ,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_FLOAT,
                                            N_("Translation step"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            1000000.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {SOCK_SHADER,
                                            N_("Translation map"),
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            0.0f,
                                            PROP_NONE,
                                            SOCK_NO_INTERNAL_LINK},
                                           {-1, ""}};

static blender::bke::bNodeSocketTemplate  sh_node_out[] = {{SOCK_RGBA, N_("OutGeo")}, {-1, ""}};

static void node_type_oct_scatter_on_surface_init(bNodeTree *ntree, bNode *node)
{
  node->custom1 = OCT_INPUT_SELECTION_METHOD_SEQUENTIAL;
  node->custom2 = OCT_SCATTER_IN_VOLUME_SHAPE_MODE_BOX;
  node->custom3 = OCT_ORIENTATION_PRIORITY_UP;
  node->custom4 = OCT_ORIENTATION_DIRECTION_MODE_DIRECTION;
  node->oct_custom1 = OCT_ORIENTATION_DIRECTION_MODE_DIRECTION;
  node->oct_custom2 = OCT_INSTANCE_TRANSFORM_MODE_FIXED;
  node->oct_custom3 = OCT_INSTANCE_TRANSFORM_MODE_FIXED;
  node->oct_custom4 = OCT_INSTANCE_TRANSFORM_MODE_FIXED;
}

void register_node_type_scatter_tool_volume(void)
{
  static blender::bke::bNodeType ntype;

  if (ntype.type != SH_NODE_OCT_SCATTER_TOOL_VOLUME)
    sh_node_type_base(&ntype,
                   SH_NODE_OCT_SCATTER_TOOL_VOLUME,
                   "Scatter on Volume",
                   NODE_CLASS_OCT_GEOMETRY);
  blender::bke::node_type_socket_templates(&ntype, sh_node_in, sh_node_out);
  node_type_size_preset(&ntype, blender::bke::eNodeSizePreset::Default);
  ntype.initfunc = (node_type_oct_scatter_on_surface_init);
  // node_type_exec(&ntype, 0, 0, 0);

  blender::bke::node_register_type(&ntype);
} /* register_node_type_scatter_tool_volume() */
