from octane.utils.octaneid import *

ENGINE_NAME = "octane"
ADDON_NAME = "octane"

DERIVED_NODE_NAMES = "DERIVED_NODE_NAMES"
DERIVED_NODE_TYPES = "DERIVED_NODE_TYPES"
DERIVED_NODE_SEPARATOR = "###DERIVED_NODE_SEPARATOR###"
OBJECT_INDEX_SEPARATOR = "###OBJECT_INDEX###"

OCTANE_HELPER_NODE_GROUP = "[OCTANE_HELPER_NODE_GROUP]"


# Add Blender Pin Type
PinType.PT_BLENDER_OUTPUT = -10000
PinType.PT_BLENDER_INPUT = -10001
PinType.PT_BLENDER_VALUES = -10002
PinType.PT_BLENDER_UTILITY = -20000


# Add Blender Node Type
NodeType.NT_BLENDER_NODE_OFFSET = -100000
NodeType.NT_BLENDER_NODE_OCTANE_PROXY = -100001
NodeType.NT_BLENDER_NODE_OBJECT_DATA = -100002
NodeType.NT_BLENDER_NODE_CAMERA_DATA = -100003
NodeType.NT_BLENDER_NODE_IMAGE_INFO = -100004
NodeType.NT_BLENDER_NODE_GET_RENDER_RESULT = -100005
NodeType.NT_BLENDER_NODE_START_RENDER = -100006
NodeType.NT_BLENDER_NODE_STOP_RENDER = -100007
NodeType.NT_BLENDER_NODE_RESET_RENDER = -100008
NodeType.NT_BLENDER_NODE_SCATTER = -100009
NodeType.NT_BLENDER_NODE_MESH = -100010
NodeType.NT_BLENDER_NODE_VOLUME = -100011


# Render Frame Data Type
class RenderFrameDataType:
    RENDER_FRAME_SIGNED_BYTE_RGBA = 0 # -127~128
    RENDER_FRAME_FLOAT_RGBA = 1
    RENDER_FRAME_FLOAT_MONO = 2


# Render Session type
class SessionType:
    UNKNOWN = 0
    VIEWPORT = 1
    FINAL_RENDER = 2
    PREVIEW = 3
    EXPORT = 4


# Blender Scene Data type
class SceneDataType:
    MESH = 0
    SUBDIVISION_MESH = 1
    OBJECT = 2


# Octane Data Block Symbol Type
class OctaneDataBlockSymbolType:
    ATTRIBUTE_ID = 0
    ATTRIBUTE_NAME = 1
    ATTRIBUTE_CUSTOM = 2
    PIN_OFFSET = 10
    PIN_ID = 10
    PIN_NAME = 11
    PIN_INDEX = 12
    PIN_DYNAMIC = 13
    PIN_CUSTOM = 14


# Legacy OctaneDataTransferObject Type
class LegacyDTOType:
    DTO_NONE = 0
    DTO_BOOL = 1
    DTO_FLOAT = 2
    DTO_FLOAT_2 = 3
    DTO_FLOAT_3 = 4
    DTO_RGB = 5
    DTO_ENUM = 6
    DTO_INT = 7
    DTO_INT_2 = 8
    DTO_INT_3 = 9
    DTO_STR = 10
    DTO_SHADER = 11


# Socket type
class SocketType:
    ST_UNKNOWN = 0
    ST_BOOL    = 1
    ST_ENUM    = 2
    ST_INT     = 3
    ST_INT2    = 4
    ST_INT3    = 5
    ST_FLOAT   = 6
    ST_FLOAT2  = 7
    ST_FLOAT3  = 8
    ST_RGBA    = 9
    ST_STRING  = 10
    ST_LINK    = 11
    ST_OUTPUT  = 100
    ST_GROUP_TITLE = 1000


# Auto Refresh Strategy
class AutoRereshStrategy:
    DISABLE = 0
    FRAME_CHANGE = 1
    ALWAYS = 2


# Pin color
class OctanePinColor:
    Default = (1, 1, 1, 1)
    GroupTitle = (0, 0, 0, 0)
    BlenderEditor = (0.7, 0.7, 0.7, 0.7)
    Bool = (0.87, 0.66, 0.83, 0.70)
    Float = (0.50, 0.70, 0.90, 0.70)
    Int = (1.00, 0.84, 0.17, 0.70)
    Transform = (0.75, 0.87, 1.00, 0.70)
    Texture = (0.75, 1.00, 0.87, 0.70)
    Emission = (1.00, 1.00, 1.00, 0.70)
    Material = (1.00, 0.95, 0.74, 0.70)
    Camera = (0.50, 1.00, 1.00, 0.70)
    Environment = (0.50, 0.50, 1.00, 0.70)
    Imager = (0.50, 1.00, 0.50, 0.70)
    Kernel = (1.00, 0.80, 0.50, 0.70)
    Geometry = (1.00, 0.74, 0.95, 0.70)
    Medium = (1.00, 0.95, 0.74, 0.70)
    PhaseFunction = (1.00, 1.00, 1.00, 0.70)
    FilmSettings = (1.00, 1.00, 1.00, 0.70)
    Enum = (1.00, 1.00, 1.00, 0.70)
    ObjectLayer = (1.00, 1.00, 1.00, 0.70)
    PostProcessing = (1.00, 0.30, 1.00, 0.70)
    RenderTarget = (0.90, 0.90, 0.90, 0.70)
    WorkPane = (1.00, 1.00, 1.00, 0.70)
    Projection = (1.00, 1.00, 1.00, 0.70)
    Displacement = (1.00, 1.00, 1.00, 0.70)
    String = (1.00, 1.00, 1.00, 0.70)
    RenderAOVs = (1.00, 1.00, 1.00, 0.70)
    RenderLayer = (0.90, 0.50, 0.00, 0.70)
    VolumeRamp = (1.00, 1.00, 1.00, 0.70)
    AnimationSettings = (1.00, 1.00, 1.00, 0.70)
    LUT = (1.00, 1.00, 1.00, 0.70)
    RenderJob = (1.00, 1.00, 1.00, 0.70)
    ToonRamp = (1.00, 1.00, 1.00, 0.70)
    BitMask = (1.00, 1.00, 1.00, 0.70)
    RoundEdges = (1.00, 1.00, 1.00, 0.70)
    MaterialLayer = (1.00, 1.00, 1.00, 0.70)
    OCIOView = (1.00, 1.00, 1.00, 0.70)
    OCIOLook = (1.00, 1.00, 1.00, 0.70)
    OCIOColorSpace = (1.00, 1.00, 1.00, 0.70)
    AOVOutputGroup = (1.00, 1.00, 1.00, 0.70)
    AOVOutput = (1.00, 1.00, 1.00, 0.70)
    CompositeTextureLayer = (1.00, 1.00, 1.00, 0.70)
    CompositeAOVLayer = (1.00, 1.00, 1.00, 0.70)


class ArrayIdentifier:
    ARRAY_INFO_POINT_DATA = "POINT"
    ARRAY_INFO_NORMAL_DATA = "NORMAL"
    ARRAY_INFO_POINT_INDEX_DATA = "POINT_INDEX"
    ARRAY_INFO_NORMAL_INDEX_DATA = "NORMAL_INDEX"
    ARRAY_INFO_VERTEX_PER_POLY_DATA = "VERTEX_PER_POLY"
    ARRAY_INFO_MAT_ID_POLY_DATA = "MATERIAL_ID_PER_POLY"
    ARRAY_INFO_OBJ_ID_POLY_DATA = "OBJECT_ID_PER_POLY"
    ARRAY_INFO_UV_DATA = "UV"
    ARRAY_INFO_UV_INDEX_DATA = "UV_INDEX"
    ARRAY_INFO_CANDIDATE_UV_DATA = "CANDIDATE_UV"
    ARRAY_INFO_CANDIDATE_UV_INDEX_DATA = "CANDIDATE_UV_INDEX"
    ARRAY_INFO_VERTEX_COLOR_DATA = "VERTEX_COLOR"
    ARRAY_INFO_VERTEX_FLOAT_DATA = "VERTEX_FLOAT"
    ARRAY_INFO_VELOCITY_DATA = "VERTEX_VELOCITY"
    ARRAY_INFO_HAIR_POINT_DATA = "HAIR_POINT"
    ARRAY_INFO_HAIR_VERTEX_PER_HAIR_DATA = "HAIR_VERTEX_PER_HAIR"
    ARRAY_INFO_HAIR_THICKNESS_DATA = "HAIR_THICKNESS"
    ARRAY_INFO_HAIR_MAT_INDEX_DATA = "HAIR_MAT_INDEX"
    ARRAY_INFO_HAIR_UV_DATA = "HAIR_UV"
    ARRAY_INFO_HAIR_W_DATA = "HAIR_W"
    ARRAY_INFO_OPENSUBDIVISION_CREASE_INDEX = "OPENSUBDIVISION_CREASE_INDEX"
    ARRAY_INFO_OPENSUBDIVISION_CREASE_SHARPNESS = "OPENSUBDIVISION_CREASE_SHARPNESS"
    ARRAY_INFO_MATRIX_DATA = "MATRIX"
    ARRAY_INFO_INSTANCE_ID_DATA = "INSTANCE_ID"
    ARRAY_INFO_SPHERE_CENTER_DATA = "SPHERE_CENTER"
    ARRAY_INFO_SPHERE_RADIUS_DATA = "SPHERE_RADIUS"
    ARRAY_INFO_SPHERE_SPEED_DATA = "SPHERE_SPEED"
    ARRAY_INFO_SPHERE_UV_DATA = "SPHERE_UV"
    ARRAY_INFO_SPHERE_VERTEX_COLOR_DATA = "SPHERE_VERTEX_COLOR"
    ARRAY_INFO_SPHERE_VERTEX_FLOAT_DATA = "SPHERE_VERTEX_FLOAT"
    ARRAY_INFO_SPHERE_MATERIAL_INDEX_DATA = "SPHERE_MATERIAL_INDEX"


# Octane NodeTree
class OctaneNodeTree:
    GENERAL = "OCTANE_TREE"
    CAMERA_IMAGER = "OCTANE_CAMERA_IMAGER_TREE"
    COMPOSITE = "OCTANE_COMPOSITE_TREE"
    KERNEL = "OCTANE_KERNEL_TREE"
    RENDER_AOV = "OCTANE_RENDER_AOV_TREE"
    BLENDER_SHADER = "OCTANE_SHADER_TREE"
    BLENDER_TEXTURE = "OCTANE_TEXTURE_TREE"


# Node Tree ID Names
class OctaneNodeTreeIDName:
    GENERAL = "octane_general_nodes"
    MATERIAL = "octane_material_nodes"
    TEXTURE = "octane_texture_nodes"
    WORLD = "octane_world_nodes"
    LIGHT = "octane_light_nodes"
    CAMERA_IMAGER = "octane_camera_imager_nodes"
    COMPOSITE = "octane_composite_nodes"
    KERNEL = "octane_kernel_nodes"
    RENDER_AOV = "octane_render_aov_nodes"        
    BLENDER_SHADER = "ShaderNodeTree"
    BLENDER_TEXTURE = "TextureNodeTree"


# Octane Preset Node Tree Names
class OctanePresetNodeTreeNames:
    KERNEL = "OCTANE_KERNEL"


# Octane Preset Node Names
class OctanePresetNodeNames:
    ENVIRONMENT = "OCTANE_BLENDER_ENVIRONMENT"
    VISIBLE_ENVIRONMENT = "OCTANE_BLENDER_VISIBLE_ENVIRONMENT"
    COMPOSITE = "OCTANE_BLENDER_RENDER_AOV_NODE"
    RENDER_AOV = "OCTANE_BLENDER_RENDER_AOV_NODE"
    CAMERA = "OCTANE_CAMERA"
    IMAGER = "OCTANE_IMAGER"
    POST_PROCESSING = "OCTANE_POST_PROCESSING"
    ANIMATION_SETTINGS = "OCTANE_ANIMATION_SETTINGS"
    RENDER_LAYER = "OCTANE_RENDER_LAYER"
    CAMERA_POSITION = "OCTANE_CAMERA_POSITION"
    CAMERA_TARGET = "OCTANE_CAMERA_TARGET"
    CAMERA_UP = "OCTANE_CAMERA_UP"


# Octane OutputNode Socket Names
class OctaneOutputNodeSocketNames:
    TEXTURE = "Texture"
    SURFACE = "Surface"
    VOLUME = "Volume"
    GEOMETRY = "Geometry"
    LIGHT = "Light"
    ENVIRONMENT = "Environment"
    VISIBLE_ENVIRONMENT = "Visible Environment"
    LEGACY_GEOMETRY = "Octane Geometry"
    LEGACY_ENVIRONMENT = "Octane Environment"
    LEGACY_VISIBLE_ENVIRONMENT = "Octane VisibleEnvironment"
    COMPOSITE = "AOVOutputGroup"
    RENDER_AOV = "RenderAOVs"


class ObjectLayerMode:
    NO_OBJECTLAYER = 0
    WITH_OBJECTLAYER = 1
    WITH_OBJECTLAYER_FOR_ORBX_PROXY = 2


class UtilsFunctionType:
    TEST = 0
    SHOW_NODEGRAPH = 1
    SHOW_NETWORK_PREFERENCE = 2
    STOP_RENDERING = 3     
    SHOW_LOG = 4
    SHOW_DEVICE_SETTINGS = 5
    FETCH_LIVEDB = 6
    SHOW_ACTIVATION = 7
    SAVE_LIVEDB = 8
    SHOW_VIEWPORT = 9
    UPDATE_RESOURCE_CACHE_SYSTEM = 10
    UPDATE_RENDER_SETTINGS = 11
    FETCH_IMAGE_INFO = 100
    FETCH_VDB_INFO = 101
    FETCH_OSL_INFO = 102
    EXPORT_OFFSET = 200
    EXPORT_ALEMBIC_START = 201
    EXPORT_ALEMBIC_END = 202
    EXPORT_ALEMBIC_WRITE_FRAME = 203
    EXPORT_ORBX_START = 204
    EXPORT_ORBX_END = 205
    EXPORT_ORBX_WRITE_FRAME = 206
    RENDER_START = 300
    RENDER_STOP = 301
    RENDER_PAUSE = 302

class RenderPassId:
    BEAUTY = 0
    BEAUTY_DENOISER_OUTPUT = 43
    DIFFUSE_DIRECT_DENOISER_OUTPUT = 44
    DIFFUSE_INDIRECT_DENOISER_OUTPUT = 45
    REFLECTION_DIRECT_DENOISER_OUTPUT = 46
    REFLECTION_INDIRECT_DENOISER_OUTPUT = 47
    EMISSION_DENOISER_OUTPUT = 76
    REMAINDER_DENOISER_OUTPUT = 49
    VOLUME_DENOISER_OUTPUT = 74
    VOLUME_EMISSION_DENOISER_OUTPUT = 75    
    

# Pin Id
P_INVALID = -1
P_UNKNOWN = 0

# Attribute Id
A_UNKNOWN = 0


# OSL Compilation Results
COMPILE_NONE = 0
COMPILE_SUCCESS = 1
COMPILE_FAILED = 2
COMPILE_FORCE = 3


# Socket colors
SOCKET_COLOR_OCIO_COLOR_SPACE = (1, 0, 1, 1)


# Render pass ID
RENDER_PASS_INVALID = -1


# Link Utility Menu
LINK_UTILITY_REMOVE = "LINK_UTILITY_REMOVE_OPERATOR"
LINK_UTILITY_DISCONNECT = "LINK_UTILITY_DISCONNECT_OPERATOR"
LINK_UTILITY_DEFAULT = "LINK_UTILITY_DEFAULT_OPERATOR"
LINK_UTILITY_REMOVE_INDEX = 10002
LINK_UTILITY_DISCONNECT_INDEX = 10001
LINK_UTILITY_DEFAULT_INDEX = 10000
LINK_UTILITY_MENU = (
    ("", "Link", ""), 
    (LINK_UTILITY_REMOVE, "Remove", "Remove nodes connected to the input", LINK_UTILITY_REMOVE_INDEX), 
    (LINK_UTILITY_DISCONNECT, "Disconnect", "Disconnect nodes connected to the input", LINK_UTILITY_DISCONNECT_INDEX),
    (LINK_UTILITY_DEFAULT, "Default", "Same effect as the 'Disconnect'", LINK_UTILITY_DEFAULT_INDEX),
)